### ISSUE TITLE
Update project status badge

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/whatdataio#2]
The project status badge says that the repo is experimental. I suggest that the repo is now "stable", and so should be updated accordingly (see https://lifecycle.r-lib.org/articles/stages.html#stable). This can be acheived by edting the README.Rmd file and running the Makefile command to remake the readme file and the site documentation.

**Comment by girijakar** [comment]
I've created some PRs, once check. If those are fine then I'll update the rest badges in your other projects.

**Comment by jeffreyhanson** [comment]
Hi @girijakar, you're a legend - thank you so much for looking into this! I really appreciate it. 

That looks great! If possible, could you please use the `brightgreen` color so follow the tidyverse lifecycle conventions, and update the URL as well? It would seem that the tidyverse lifecycle webpage has been updated so the current URL is broken.

Specifically, could you please change it to this?

```
[![lifecycle](https://img.shields.io/badge/Lifecycle-stable-brightgreen.svg)](https://lifecycle.r-lib.org/articles/stages.html)
````

**Comment by girijakar** [comment]
I've updated the URL. Check once the PR.

**Comment by jeffreyhanson** [comment]
Great - thanks! I'm sorry, I just noticed that the PR has updated the `README.md` file. Could you please make this change to the `README.Rmd` file too? This is because the `README.md` file is automatically generated based on the `README.Rmd` - so updating the project documentation will would overwrite and revert these changes. Sorry for not noticing this earlier.
